--- # block separator
- hosts: web
  become: true
  become_user: root
  tasks:
    - apk: name=nginx state=present
- hosts: db
  become: true
  become_user: root
  tasks:
    - apk: name=mysql state=present
