--- # block separator
- hosts: web
  become: true
  become_user: root
  tasks:
    - apk: name=nginx state=present
    - name: start apache and enabled
      service: name=nginx state=started enabled=yes
- hosts: db
  become: true
  become_user: root
  tasks:
    - apk: name=mysql state=present
      service: name=mysqld state=started enabled=yes
