--- # block separator
- hosts: all
  become: true
  become_user: root
  vars:
    users: 
      - "hirorok"
      - "ansible"
  tasks:
    - name: 'add users'
      user: name="{{item}}" state=present
      with_items: '{{users}}'
    - name: "install timezone"
      apk: name=tzdata state=present
    - name: "copy timezone filer"
      shell: cp /usr/share/zoneinfo/Japan /etc/localtime
      args:
        creates: /etc/localtime/Japan
- hosts: web
  become: true
  become_user: root
  tasks:
    - name: add user
      user: name=www 
    - name: "install nginx"
      apk: name=nginx state=present
    - name: copy conf file
      copy: 
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: copy index.html
      copy: 
        src: ./index.html
        dest: /www
    - name: chmod
      file:
          path: /www
          state: directory
          mode: 0755
    - name: chmod 2
      file:
        path: /var/lib/nginx
        owner: www
        group: www
        mode: 0644
    - name: "start nginx"
      service: name=nginx state=started enabled=yes
    - name: "php instalal"
      apk: name="{{item}}" state=present
      with_items:
        - php
      notify:
      - restart nginx
  handlers: 
    - name: restart nginx
      service: name=nginx state=restarted
- hosts: db
  become: true
  become_user: root
  tasks:
    - name: "install mariadb" 
      apk: name="{{item}}" state=present
      with_items:
        - mariadb
        - mariadb-client
        - py-mysqldb
    - name: "start mariadb" 
      service: name=mariadb state=started enabled=yes
    - name: "create db"
      mysql_db: name=mydb state=present
    - name: "add user"
      mysql_user: name=dbuser password=password priv=mydb.*:ALL state=present
