--- # block separator
- hosts: web
  become: true
  become_user: root
  tasks:
    - name: "install nginx"
      apk: name=nginx state=present
    - name: "start nginx"
      service: name=nginx state=started enabled=yes
    - name: php install
      apk: name={{item}} state=latest
      with_items:
        - php
        - php-devel
        - php-mbstring
        - php-mysql
- hosts: db
  become: true
  become_user: root
  tasks:
    - name: "install mariadb" 
      apk: name="{{item}}" state=present
      with_items:
        - mariadb
        - mariadb-client
        - py-mysqldb
    - name: "start mariadb" 
      service: name=mariadb state=started enabled=yes
    - name: "create db"
      mysql_db: name=mydb state=present
    - name: "add user"
      mysql_user: name=dbuser password=password priv=mydb.*:ALL state=present
