--- # block separator
- hosts: web
  become: true
  become_user: root
  tasks:
    - name: start apache and enabled
    - apk: name=nginx state=present
    - service: name=nginx state=started enabled=yes
- hosts: db
  become: true
  become_user: root
  tasks:
    - apk: name=mysql state=present
      service: name=mariadb state=started enabled=yes
