--- # block separator
- hosts: all
  become: true
  become_user: root
  vars:
    users: 
      - "hirorok"
      - "ansible"
  tasks:
    - name: 'add users'
      user: name="{{item}}" state=absense
      with_items: '{{users}}'

